// iter 132 — every scaffolded harness must ship .claude-plugin/plugin.json
// so `claude -p --plugin-dir <harness>` works without manual setup.
//
// This is the regression guard for the iter-131/132 work:
//   - iter 131: minimal template gets .claude-plugin/plugin.json.tmpl
//   - iter 132: ALL verticals get it (regenerated + hand-authored)
//
// The check is two-layered:
//   1. STATIC — every template's manifest.json lists the .claude-plugin entry
//      and the .tmpl file actually exists on disk.
//   2. RUNTIME — when scaffolded, the rendered .claude-plugin/plugin.json is
//      valid JSON, has {{name}} + {{description}} substituted, and carries
//      the metaharness branding.
//
// If this test ever goes red, either a new template skipped the propagation
// step in gen-templates.mjs, or someone deleted the entry by hand.
import { describe, it, expect } from 'vitest';
import { readdirSync, readFileSync, existsSync, mkdtempSync, rmSync } from 'node:fs';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
import { execFileSync } from 'node:child_process';

const TEMPLATES_ROOT = join(__dirname, '..', 'templates');
const BIN = join(__dirname, '..', 'dist', 'bin.js');

function listTemplateDirs(): string[] {
  return readdirSync(TEMPLATES_ROOT).filter((d) => {
    const p = join(TEMPLATES_ROOT, d);
    return existsSync(join(p, 'manifest.json'));
  });
}

describe('iter 132 — .claude-plugin/plugin.json coverage', () => {
  const templateDirs = listTemplateDirs();

  it('finds ALL templates on disk (sanity check)', () => {
    expect(templateDirs.length).toBeGreaterThanOrEqual(20);
  });

  it.each(templateDirs)('%s manifest.json lists .claude-plugin/plugin.json.tmpl', (dir) => {
    const manifestPath = join(TEMPLATES_ROOT, dir, 'manifest.json');
    const m = JSON.parse(readFileSync(manifestPath, 'utf-8'));
    const entry = m.files.find((f: { src: string }) => f.src === '.claude-plugin/plugin.json.tmpl');
    expect(entry, `${dir}/manifest.json must include .claude-plugin/plugin.json.tmpl`).toBeDefined();
    expect(entry.dst).toBe('.claude-plugin/plugin.json');
    expect(entry.render).toBe(true);
  });

  it.each(templateDirs)('%s ships the .tmpl file on disk', (dir) => {
    const tmplPath = join(TEMPLATES_ROOT, dir, '.claude-plugin', 'plugin.json.tmpl');
    expect(existsSync(tmplPath), `${tmplPath} must exist`).toBe(true);
    const body = readFileSync(tmplPath, 'utf-8');
    // Must be valid JSON with {{name}} + {{description}} placeholders pre-substitution.
    expect(body).toMatch(/\{\{name\}\}/);
    expect(body).toMatch(/\{\{description\}\}/);
    const parsed = JSON.parse(body);
    expect(parsed.author?.displayName).toBe('Generated by metaharness');
    expect(parsed.categories).toContain('agent-harness');
    expect(parsed.categories).toContain('metaharness-scaffold');
    expect(parsed.tags).toContain('metaharness');
    expect(parsed.license).toBe('MIT');
  });

  it('scaffold emits a rendered .claude-plugin/plugin.json with name substituted', () => {
    if (!existsSync(BIN)) return; // skip if not built
    const tmpDir = mkdtempSync(join(tmpdir(), 'plugin-coverage-'));
    try {
      const name = 'plugincov-bot';
      execFileSync('node', [BIN, name, '--template', 'minimal', '--host', 'claude-code', '--force'], {
        cwd: tmpDir,
        encoding: 'utf-8',
        timeout: 30000,
      });
      const pluginPath = join(tmpDir, name, '.claude-plugin', 'plugin.json');
      expect(existsSync(pluginPath), 'scaffold must emit .claude-plugin/plugin.json').toBe(true);
      const rendered = JSON.parse(readFileSync(pluginPath, 'utf-8'));
      expect(rendered.name).toBe(name);
      expect(rendered.description).not.toMatch(/\{\{/);  // no unrendered placeholders
      expect(rendered.author.url).toBe('https://www.npmjs.com/package/metaharness');
    } finally {
      rmSync(tmpDir, { recursive: true, force: true });
    }
  });
});
